### ISSUE TITLE
some initial notes 

### ISSUE THREAD

**Issue by topepo** [tidymodels/applicable#1]
Based on our previous conversation

* I think that, for unsupervised models, we can use `y = NA` in [these calls](https://github.com/marlycormar/applicable/blob/e6706653176615eb1448b2d25f3fc993ea63210a/R/fit-interface.R#L64
) to `mold()`. 

* For [this line](https://github.com/marlycormar/applicable/blob/e6706653176615eb1448b2d25f3fc993ea63210a/R/fit-bridge.R#L5), you won't need to pass in `outcome`.  The line `outcome <- processed$outcomes[[1]]` won't be needed either. 

* `fit-implementation.R` would include the call to `prcomp()` and that object would be returned [here](https://github.com/marlycormar/applicable/blob/e6706653176615eb1448b2d25f3fc993ea63210a/R/fit-bridge.R#L8) (instead of the `coefs` thing that gets automatically populated)

* Since we will have multiple `ad_*` functions, you may want to combine the `fit-*` files into a single file for PCA (same for the `predict-*` files too).

**Comment by marlycormar** [comment]
Thanks Max! closing this issue as these notes have been already implemented.
